apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-main
  name: nginx-maindeploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
          


