apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  type: NodePort
  ports:
  - name: http
    port: 8161
    nodePort: 30010

  - name: endpoint
    port: 61616

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  type: ClusterIP
  ports:
  - name: http
    port: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30020
---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30080



    


